generator: adversarial
output_dir: generated_datasets/adv_mnist_8.pt
N: 100

attack:
  method: pgd
  epsilon: 0.03137  # 8 / 255
  pgd_steps: 5

dataset:
  _target_: torchvision.datasets.MNIST
  root: ./datasets
  train: false
  download: true

model:
  _target_: model.mnist.load_model
  pretrained: true
