generator: perturb
output_dir: generated_datasets/perturb_cifar_16.pt
N: 100
epsilon: 0.06274  # 16 / 255

dataset:
  _target_: torchvision.datasets.CIFAR10
  root: ./datasets
  train: false
  download: true
