generator: perturb
output_dir: generated_datasets/perturb_mnist_8.pt
N: 100
epsilon: 0.03137  # 8 / 255

dataset:
  _target_: torchvision.datasets.MNIST
  root: ./datasets
  train: false
  download: true
