generator: perturb
output_dir: generated_datasets/perturb_mnist_4.pt
N: 100
epsilon: 0.01569  # 4 / 255

dataset:
  _target_: torchvision.datasets.MNIST
  root: ./datasets
  train: false
  download: true
